interface Lookup {
  [key: string]: string;
}

export const SKILL_LOOKUP: Lookup = {
  punt_power: 'Punt Power',
  tackle_strip: 'Strip Technique',
  leadership: 'Leadership',
  run_block_awareness: 'Run Blk Awr',
  coverage_interception: 'Intercepting',
  pass_rush_power: 'Pass Rush Power',
  route_elusiveness: 'Route Elusiveness',
  catch_consistency: 'Rec Consistency',
  snap_reaction: 'Snap Reaction',
  block_consistency: 'Block Consistency',
  pass_block_awareness: 'Pass Blk Awr',
  diving: 'Diving',
  kick_consistency: 'Kick Consistency',
  pass_evasiveness: 'Pocket Awr',
  toughness: 'Toughness',
  pass_accuracy: 'Pass Accuracy',
  kick_power: 'Field Goal Power',
  pass_technique: 'Pass Technique',
  carry_awareness: 'Carrying Awr',
  route_technique: 'Route Technique',
  punt_consistency: 'Punt Consistency',
  carry_grip: 'Carrying Grip',
  carry_elusiveness: 'Elusive Running',
  defense_consistency: 'Def Consistency',
  run_block_power: 'Run Blk Power',
  tackle_power: 'Power Tackling',
  pass_block_technique: 'Pass Blk Tech',
  tackle_awareness: 'Pursuit',
  break_run_block: 'Break Run Blk',
  conditioning: 'Conditioning',
  tackle_technique: 'Tackling Tech',
  catch_hands: 'Receiving Hands',
  catch_grip: 'Receiving Grip',
  return_awareness: 'Return Awr',
  man_coverage_awareness: 'Man Awareness',
  pass_consistency: 'Pass Consistency',
  footwork: 'Footwork',
  punt_hands: 'Punt Hands',
  intimidation: 'Intimidation',
  zone_coverage_awareness: 'Zone Awareness',
  pass_power: 'Pass Power',
  pass_rush_deflection: 'Pass Rush Defl',
  quickness: 'Quickness',
  balance: 'Balance',
  vertical: 'Vertical',
  pass_carry_power: 'Drop Back Power',
  punt_accuracy: 'Punt Accuracy',
  hold_ground: 'Hold Ground',
  kickoff_power: 'Kickoff Power',
  pass_awareness: 'Pass Awareness',
  blitz_awareness: 'Blitz Awr',
  carry_power: 'Power Running',
  pass_block_power: 'Pass Blk Power',
  catch_awareness: 'Rec Awareness',
  kick_accuracy: 'Kick Accuracy',
  pass_grip: 'Drop Back Grip',
  run_block_technique: 'Run Blk Tech',
  heart: 'Heart',
  catch_in_traffic: 'Catch in Traffic',
  coverage_technique: 'Coverage Tech',
  lead_block_awareness: 'Lead Blk Awr',
  tackle_grip: 'Tackling Grip',
  sprinting: 'Sprinting',
  pass_rush_technique: 'Pass Rush Tech',
  coverage_deflection: 'Deflecting',
};

export const TRAIT_LOOKUP: Lookup = {
  superstar_glam: 'Superstar',
  superstar_avg: 'Superstar',
  hb_rushing_back: 'Rusher',
  hb_unpredictable: 'Unpr-edic-table',
  unpredictable: 'Unpr-edic-table',
  qb_precision_passer: 'Precision Passer',
  qb_pocket_passer: 'Pocket Passer',
  te_receiver: 'Receiving Specialist',
  nerves_of_steel: 'Nerves of Steel',
  soft_hands: 'Soft Hands',
  wr_shifty: 'Shifty',
};
