export const getSkillMins = (position: string) => {
  const positionFactors: { [pos: string]: { [key: string]: number } } = {
    QB: {
      pass_technique: 100.0,
      pass_accuracy: 90.0,
      pass_power: 60.0,
      pass_consistency: 100.0,
      pass_grip: -1.0,
      pass_evasiveness: 50.0,
      pass_carry_power: -1.0,
      pass_awareness: 40.0,
      carry_grip: -1.0,
      carry_power: -1.0,
      carry_elusiveness: -1.0,
      carry_awareness: -1.0,
      balance: 30.0,
      footwork: 20.0,
      quickness: -1.0,
      sprinting: -1.0,
      conditioning: 50.0,
      toughness: 30.0,
      heart: 50.0,
      intimidation: -1.0,
      leadership: 80.0,
    },
    HB: {
      carry_grip: 60.0,
      carry_power: 100.0,
      carry_elusiveness: 80.0,
      carry_awareness: 80.0,
      return_awareness: -1.0,
      route_technique: -1.0,
      route_elusiveness: -1.0,
      catch_hands: -1.0,
      catch_in_traffic: -1.0,
      catch_grip: -1.0,
      catch_awareness: -1.0,
      catch_consistency: -1.0,
      pass_block_technique: -1.0,
      pass_block_power: -1.0,
      pass_block_awareness: -1.0,
      run_block_technique: -1.0,
      run_block_power: -1.0,
      run_block_awareness: -1.0,
      lead_block_awareness: -1.0,
      block_consistency: -1.0,
      balance: 80.0,
      footwork: 50.0,
      quickness: 40.0,
      sprinting: 40.0,
      vertical: -1.0,
      diving: -1.0,
      conditioning: 100.0,
      toughness: 60.0,
      snap_reaction: -1.0,
      heart: 30.0,
      intimidation: 40.0,
    },
  };
  return positionFactors[position];
};
