export const getSkillMins = (position: string, template: string) => {
  const positionFactors: { [pos: string]: { [temp: string]: { [key: string]: number } } } = {
    // QB: {
    //   Pocket: {
    //     pass_technique: 0.8,
    //     pass_accuracy: 0.8,
    //     pass_power: 1.0,
    //     pass_consistency: 0.8,
    //     pass_grip: 3.0,
    //     pass_evasiveness: 3.0,
    //     pass_carry_power: 3.0,
    //     pass_awareness: 2.0,
    //     carry_grip: 20.0,
    //     carry_power: 20.0,
    //     carry_elusiveness: 20.0,
    //     carry_awareness: 20.0,
    //     balance: 20.0,
    //     footwork: 20.0,
    //     quickness: 20.0,
    //     sprinting: 20.0,
    //     conditioning: 2.5,
    //     toughness: 5.0,
    //     heart: 2.0,
    //     intimidation: 20.0,
    //     leadership: 2.5,
    //   },
    // },
    HB: {
      Slombo: {
        carry_grip: 80.0,
        carry_power: 95.0,
        carry_elusiveness: 80.0,
        carry_awareness: 80.0,
        return_awareness: -1.0,
        route_technique: -1.0,
        route_elusiveness: -1.0,
        catch_hands: -1.0,
        catch_in_traffic: -1.0,
        catch_grip: -1.0,
        catch_awareness: -1.0,
        catch_consistency: -1.0,
        pass_block_technique: -1.0,
        pass_block_power: -1.0,
        pass_block_awareness: -1.0,
        run_block_technique: -1.0,
        run_block_power: -1.0,
        run_block_awareness: -1.0,
        lead_block_awareness: -1.0,
        block_consistency: -1.0,
        balance: 80.0,
        footwork: 75.0,
        quickness: 40.0,
        sprinting: 40.0,
        vertical: -1.0,
        diving: -1.0,
        conditioning: 96.0,
        toughness: 40.0,
        snap_reaction: -1.0,
        heart: 30.0,
        intimidation: -1.0,
      },
    },
    // FB: {
    //   Norm: {
    //     pass_block_technique: 1.0,
    //     pass_block_power: 1.0,
    //     pass_block_awareness: 1.0,
    //     run_block_technique: 1.0,
    //     run_block_power: 1.0,
    //     run_block_awareness: 1.0,
    //     lead_block_awareness: 1.0,
    //     block_consistency: 1.0,
    //     route_technique: 1.0,
    //     route_elusiveness: 1.0,
    //     catch_hands: 1.0,
    //     catch_in_traffic: 1.0,
    //     catch_grip: 1.0,
    //     catch_awareness: 1.0,
    //     catch_consistency: 1.0,
    //     carry_grip: 2.5,
    //     carry_power: 0.4,
    //     carry_elusiveness: 0.5,
    //     carry_awareness: 2.2,
    //     return_awareness: 1.0,
    //     balance: 1.3,
    //     footwork: 1.0,
    //     quickness: 1.2,
    //     sprinting: 1.0,
    //     vertical: 1.0,
    //     diving: 1.0,
    //     conditioning: 1.2,
    //     toughness: 1.0,
    //     snap_reaction: 1.0,
    //     heart: 1.0,
    //     intimidation: 1.0,
    //   },
    // },
    // TE: {
    //   Possession: {
    //     route_technique: 1.0,
    //     route_elusiveness: 1.0,
    //     catch_hands: 0.8,
    //     catch_in_traffic: 1.2,
    //     catch_grip: 2.0,
    //     catch_awareness: 3.0,
    //     catch_consistency: 1.0,
    //     pass_block_technique: 20.0,
    //     pass_block_power: 20.0,
    //     pass_block_awareness: 20.0,
    //     run_block_technique: 20.0,
    //     run_block_power: 20.0,
    //     run_block_awareness: 20.0,
    //     lead_block_awareness: 20.0,
    //     block_consistency: 20.0,
    //     carry_grip: 4.0,
    //     carry_power: 20.0,
    //     carry_elusiveness: 20.0,
    //     carry_awareness: 20.0,
    //     return_awareness: 20.0,
    //     balance: 2.0,
    //     footwork: 1.5,
    //     quickness: 1.0,
    //     sprinting: 0.8,
    //     vertical: 2.0,
    //     diving: 2.0,
    //     conditioning: 0.8,
    //     toughness: 2.5,
    //     snap_reaction: 1.5,
    //     heart: 1.5,
    //     intimidation: 20.0,
    //   },
    // },
    // WR: {
    //   Possession: {
    //     route_technique: 1.0,
    //     route_elusiveness: 1.5,
    //     catch_hands: 1.0,
    //     catch_in_traffic: 0.9,
    //     catch_grip: 1.5,
    //     catch_awareness: 3.0,
    //     catch_consistency: 1.0,
    //     carry_grip: 3.5,
    //     carry_power: 20.0,
    //     carry_elusiveness: 20.0,
    //     carry_awareness: 20.0,
    //     return_awareness: 20.0,
    //     run_block_technique: 20.0,
    //     run_block_power: 20.0,
    //     run_block_awareness: 20.0,
    //     block_consistency: 20.0,
    //     balance: 2.5,
    //     footwork: 3.5,
    //     quickness: 1.5,
    //     sprinting: 1.0,
    //     vertical: 3.5,
    //     diving: 3.5,
    //     conditioning: 1.2,
    //     toughness: 3.0,
    //     snap_reaction: 2.0,
    //     heart: 3.0,
    //     intimidation: 20.0,
    //   },
    // C: {
    //   Norm: {
    //     pass_block_technique: 1.0,
    //     pass_block_power: 1.0,
    //     pass_block_awareness: 1.0,
    //     run_block_technique: 1.0,
    //     run_block_power: 1.0,
    //     run_block_awareness: 1.0,
    //     block_consistency: 1.0,
    //     balance: 1.3,
    //     footwork: 1.0,
    //     quickness: 1.2,
    //     sprinting: 1.0,
    //     conditioning: 1.2,
    //     toughness: 1.0,
    //     snap_reaction: 1.0,
    //     heart: 1.0,
    //     intimidation: 1.0,
    //   },
    // },
    // G: {
    //   Norm: {
    //     pass_block_technique: 1.0,
    //     pass_block_power: 1.0,
    //     pass_block_awareness: 1.0,
    //     run_block_technique: 1.0,
    //     run_block_power: 1.0,
    //     run_block_awareness: 1.0,
    //     lead_block_awareness: 1.0,
    //     block_consistency: 1.0,
    //     balance: 1.3,
    //     footwork: 1.0,
    //     quickness: 1.2,
    //     sprinting: 1.0,
    //     conditioning: 1.2,
    //     toughness: 1.0,
    //     snap_reaction: 1.0,
    //     heart: 1.0,
    //     intimidation: 1.0,
    //   },
    // },
    OT: {
      Norm: {
        pass_block_technique: 40.0,
        pass_block_power: 30.0,
        pass_block_awareness: -1.0,
        run_block_technique: 70.0,
        run_block_power: 30.0,
        run_block_awareness: 35.0,
        lead_block_awareness: 30.0,
        block_consistency: 98.0,
        balance: 70.0,
        footwork: 40.0,
        quickness: 30.0,
        sprinting: -1.0,
        conditioning: 60.0,
        toughness: 98.0,
        snap_reaction: 80.0,
        heart: 70.0,
        intimidation: -1.0,
      },
    },
    DT: {
      Norm: {
        pass_rush_technique: 80.0,
        pass_rush_power: -1.0,
        pass_rush_deflection: -1.0,
        break_run_block: 100.0,
        blitz_awareness: 30.0,
        hold_ground: 25.0,
        tackle_awareness: 80.0,
        defense_consistency: 75.0,
        tackle_technique: 79.0,
        tackle_power: 40.0,
        tackle_strip: -1.0,
        tackle_grip: 50.0,
        balance: 90.0,
        footwork: 40.0,
        quickness: 30.0,
        sprinting: -1.0,
        vertical: -1.0,
        diving: -1.0,
        conditioning: 60.0,
        toughness: 80.0,
        snap_reaction: 60.0,
        heart: 50.0,
        intimidation: -1.0,
      },
    },
    DE: {
      Spin: {
        pass_rush_technique: 100.0,
        pass_rush_power: -1.0,
        pass_rush_deflection: -1.0,
        break_run_block: 50.0,
        blitz_awareness: 30.0,
        hold_ground: 25.0,
        tackle_awareness: 50.0,
        defense_consistency: 50.0,
        zone_coverage_awareness: -1.0,
        coverage_deflection: -1.0,
        coverage_interception: -1.0,
        tackle_technique: 60.0,
        tackle_power: 25.0,
        tackle_strip: 25.0,
        tackle_grip: 25.0,
        balance: 70.0,
        footwork: 50.0,
        quickness: 40.0,
        sprinting: 40.0,
        vertical: -1.0,
        diving: 30.0,
        conditioning: 65.0,
        toughness: 40.0,
        snap_reaction: 100.0,
        heart: 40.0,
        intimidation: -1.0,
      },
    },
    // LB: {
    //   Norm: {
    //     tackle_technique: 1.0,
    //     tackle_power: 1.0,
    //     tackle_strip: 1.0,
    //     tackle_grip: 1.0,
    //     break_run_block: 1.0,
    //     blitz_awareness: 1.0,
    //     hold_ground: 1.0,
    //     tackle_awareness: 1.0,
    //     defense_consistency: 1.0,
    //     man_coverage_awareness: 1.0,
    //     zone_coverage_awareness: 1.0,
    //     coverage_technique: 1.0,
    //     coverage_deflection: 1.0,
    //     coverage_interception: 1.0,
    //     pass_rush_technique: 1.0,
    //     pass_rush_power: 1.0,
    //     pass_rush_deflection: 1.0,
    //     balance: 1.3,
    //     footwork: 1.0,
    //     quickness: 1.2,
    //     sprinting: 1.0,
    //     vertical: 1.0,
    //     diving: 1.0,
    //     conditioning: 1.2,
    //     toughness: 1.0,
    //     snap_reaction: 1.0,
    //     heart: 1.0,
    //     intimidation: 1.0,
    //   },
    // },
    // CB: {
    //   Norm: {
    //     man_coverage_awareness: 1.0,
    //     zone_coverage_awareness: 1.0,
    //     coverage_technique: 1.0,
    //     coverage_deflection: 1.0,
    //     coverage_interception: 1.0,
    //     tackle_technique: 1.0,
    //     tackle_power: 1.0,
    //     tackle_strip: 1.0,
    //     tackle_grip: 1.0,
    //     break_run_block: 1.0,
    //     blitz_awareness: 1.0,
    //     hold_ground: 1.0,
    //     tackle_awareness: 1.0,
    //     defense_consistency: 1.0,
    //     pass_rush_technique: 1.0,
    //     pass_rush_power: 1.0,
    //     pass_rush_deflection: 1.0,
    //     carry_grip: 2.5,
    //     carry_power: 0.4,
    //     carry_elusiveness: 0.5,
    //     return_awareness: 2.2,
    //     balance: 1.3,
    //     footwork: 1.0,
    //     quickness: 1.2,
    //     sprinting: 1.0,
    //     vertical: 1.0,
    //     diving: 1.0,
    //     conditioning: 1.2,
    //     toughness: 1.0,
    //     snap_reaction: 1.0,
    //     heart: 1.0,
    //     intimidation: 1.0,
    //   },
    // },
    // SS: {
    //   Norm: {
    //     man_coverage_awareness: 1.0,
    //     zone_coverage_awareness: 1.0,
    //     coverage_technique: 1.0,
    //     coverage_deflection: 1.0,
    //     coverage_interception: 1.0,
    //     tackle_technique: 1.0,
    //     tackle_power: 1.0,
    //     tackle_strip: 1.0,
    //     tackle_grip: 1.0,
    //     break_run_block: 1.0,
    //     blitz_awareness: 1.0,
    //     hold_ground: 1.0,
    //     tackle_awareness: 1.0,
    //     defense_consistency: 1.0,
    //     pass_rush_technique: 1.0,
    //     pass_rush_power: 1.0,
    //     pass_rush_deflection: 1.0,
    //     return_awareness: 2.2,
    //     balance: 1.3,
    //     footwork: 1.0,
    //     quickness: 1.2,
    //     sprinting: 1.0,
    //     vertical: 1.0,
    //     diving: 1.0,
    //     conditioning: 1.2,
    //     toughness: 1.0,
    //     snap_reaction: 1.0,
    //     heart: 1.0,
    //     intimidation: 1.0,
    //   },
    // },
    // FS: {
    //   Norm: {
    //     man_coverage_awareness: 1.0,
    //     zone_coverage_awareness: 1.0,
    //     coverage_technique: 1.0,
    //     coverage_deflection: 1.0,
    //     coverage_interception: 1.0,
    //     tackle_technique: 1.0,
    //     tackle_power: 1.0,
    //     tackle_strip: 1.0,
    //     tackle_grip: 1.0,
    //     break_run_block: 1.0,
    //     blitz_awareness: 1.0,
    //     hold_ground: 1.0,
    //     tackle_awareness: 1.0,
    //     defense_consistency: 1.0,
    //     pass_rush_technique: 1.0,
    //     pass_rush_power: 1.0,
    //     pass_rush_deflection: 1.0,
    //     return_awareness: 2.2,
    //     balance: 1.3,
    //     footwork: 1.0,
    //     quickness: 1.2,
    //     sprinting: 1.0,
    //     vertical: 1.0,
    //     diving: 1.0,
    //     conditioning: 1.2,
    //     toughness: 1.0,
    //     snap_reaction: 1.0,
    //     heart: 1.0,
    //     intimidation: 1.0,
    //   },
    // },
    K: {
      Accurate: {
        kick_accuracy: 100.0,
        kick_power: 45.0,
        kick_consistency: 90.0,
        kickoff_power: 45.0,
        tackle_technique: -1.0,
        tackle_power: -1.0,
        tackle_strip: -1.0,
        tackle_grip: -1.0,
        balance: -1.0,
        footwork: -1.0,
        quickness: -1.0,
        sprinting: -1.0,
        vertical: -1.0,
        diving: -1.0,
        conditioning: 30.0,
        toughness: -1.0,
        snap_reaction: -1.0,
        heart: 60.0,
        intimidation: -1.0,
      },
    },
  };
  return positionFactors[position][template];
};
