import { Player } from './player';

export const getBasePlayers = (position: string): Player => {
  const basePlayers: { [key: string]: Player } = {
    QB: {
      position: 'QB',
      height: 78,
      weight: 232,
      strength: 1,
      speed: 1,
      agility: 10,
      stamina: 6,
      awareness: 7,
      confidence: 10,
      trait1: 'superstar_glam',
      trait2: 'qb_pocket_passer',
      trait3: 'early_bloomer',
    },
    HB: {
      position: 'HB',
      height: 66,
      weight: 188,
      strength: 10,
      speed: 1,
      agility: 10,
      stamina: 10,
      awareness: 3,
      confidence: 1,
      trait1: 'superstar_glam',
      trait2: 'hb_rushing_back',
      trait3: 'unpredictable',
    },
    FB: {
      position: 'FB',
      height: 70,
      weight: 220,
      strength: 8,
      speed: 8,
      agility: 10,
      stamina: 2,
      awareness: 4,
      confidence: 3,
      trait1: 'ol_tech_blocker',
      trait2: 'thick_skin',
      trait3: 'jittery',
    },
    TE: {
      position: 'TE',
      height: 80,
      weight: 246,
      strength: 1,
      speed: 1,
      agility: 8,
      stamina: 5,
      awareness: 10,
      confidence: 10,
      trait1: 'superstar_avg',
      trait2: 'natural',
      trait3: 'te_receiver',
    },
    WR: {
      position: 'WR',
      height: 78,
      weight: 195,
      strength: 1,
      speed: 1,
      agility: 7,
      stamina: 6,
      awareness: 10,
      confidence: 10,
      trait1: 'superstar_avg',
      trait2: 'natural',
      trait3: 'wr_shifty',
    },
    DT: {
      position: 'DT',
      height: 72,
      weight: 253,
      strength: 1,
      speed: 1,
      agility: 10,
      stamina: 8,
      awareness: 10,
      confidence: 5,
      trait1: 'superstar_nonglam',
      trait2: 'dl_technique_man',
      trait3: 'natural',
    },
    DE: {
      position: 'DE',
      height: 80,
      weight: 285,
      strength: 1,
      speed: 3,
      agility: 10,
      stamina: 1,
      awareness: 10,
      confidence: 10,
      trait1: 'superstar_nonglam',
      trait2: 'dl_technique_man',
      trait3: 'jittery',
    },
    LB: {
      position: 'LB',
      height: 78,
      weight: 266,
      strength: 1,
      speed: 5,
      agility: 10,
      stamina: 6,
      awareness: 10,
      confidence: 3,
      trait1: 'superstar_glam',
      trait2: 'natural',
      trait3: 'workhorse',
    },
    CB: {
      position: 'CB',
      height: 75,
      weight: 184,
      strength: 1,
      speed: 1,
      agility: 10,
      stamina: 7,
      awareness: 10,
      confidence: 6,
      trait1: 'superstar_avg',
      trait2: 'natural',
      trait3: 'egotist',
    },
    SS: {
      position: 'SS',
      height: 78,
      weight: 220,
      strength: 1,
      speed: 7,
      agility: 9,
      stamina: 2,
      awareness: 10,
      confidence: 6,
      trait1: 'superstar_avg',
      trait2: 'natural',
      trait3: 'workhorse',
    },
    FS: {
      position: 'FS',
      height: 77,
      weight: 201,
      strength: 1,
      speed: 7,
      agility: 9,
      stamina: 2,
      awareness: 10,
      confidence: 6,
      trait1: 'superstar_avg',
      trait2: 'natural',
      trait3: 'workhorse',
    },
    C: {
      position: 'C',
      height: 78,
      weight: 320,
      strength: 6,
      speed: 1,
      agility: 10,
      stamina: 1,
      awareness: 7,
      confidence: 10,
      trait1: 'ol_tech_blocker',
      trait2: 'early_bloomer',
      trait3: 'thick_skin',
    },
    G: {
      position: 'G',
      height: 78,
      weight: 320,
      strength: 6,
      speed: 1,
      agility: 10,
      stamina: 1,
      awareness: 7,
      confidence: 10,
      trait1: 'ol_tech_blocker',
      trait2: 'early_bloomer',
      trait3: 'thick_skin',
    },
    OT: {
      position: 'OT',
      height: 81,
      weight: 340,
      strength: 4,
      speed: 1,
      agility: 10,
      stamina: 6,
      awareness: 4,
      confidence: 10,
      trait1: 'ol_tech_blocker',
      trait2: 'early_bloomer',
      trait3: 'thick_skin',
    },
    K: {
      position: 'K',
      height: 77,
      weight: 254,
      strength: 10,
      speed: 1,
      agility: 10,
      stamina: 1,
      awareness: 3,
      confidence: 10,
      trait1: 'k_leg_of_steel',
      trait2: 'early_bloomer',
      trait3: 'easy_going',
    },
    P: {
      position: 'P',
      height: 77,
      weight: 254,
      strength: 10,
      speed: 1,
      agility: 1,
      stamina: 10,
      awareness: 3,
      confidence: 10,
      trait1: 'k_leg_of_steel',
      trait2: 'early_bloomer',
      trait3: 'easy_going',
    },
  };

  return basePlayers[position];
};
