interface Lookup {
  [key: string]: any;
}

export const SKILL_LOOKUP: Lookup = {
  punt_power: 'Punt Power',
  tackle_strip: 'Strip Technique',
  leadership: 'Leadership',
  run_block_awareness: 'Run Blk Awr',
  coverage_interception: 'Intercepting',
  pass_rush_power: 'Pass Rush Power',
  route_elusiveness: 'Route Elusiveness',
  catch_consistency: 'Rec Consistency',
  snap_reaction: 'Snap Reaction',
  block_consistency: 'Block Consistency',
  pass_block_awareness: 'Pass Blk Awr',
  diving: 'Diving',
  kick_consistency: 'Kick Consistency',
  pass_evasiveness: 'Pocket Awr',
  toughness: 'Toughness',
  pass_accuracy: 'Pass Accuracy',
  kick_power: 'Field Goal Power',
  pass_technique: 'Pass Technique',
  carry_awareness: 'Carrying Awr',
  route_technique: 'Route Technique',
  punt_consistency: 'Punt Consistency',
  carry_grip: 'Carrying Grip',
  carry_elusiveness: 'Elusive Running',
  defense_consistency: 'Def Consistency',
  run_block_power: 'Run Blk Power',
  tackle_power: 'Power Tackling',
  pass_block_technique: 'Pass Blk Tech',
  tackle_awareness: 'Pursuit',
  break_run_block: 'Break Run Blk',
  conditioning: 'Conditioning',
  tackle_technique: 'Tackling Tech',
  catch_hands: 'Receiving Hands',
  catch_grip: 'Receiving Grip',
  return_awareness: 'Return Awr',
  man_coverage_awareness: 'Man Awareness',
  pass_consistency: 'Pass Consistency',
  footwork: 'Footwork',
  punt_hands: 'Punt Hands',
  intimidation: 'Intimidation',
  zone_coverage_awareness: 'Zone Awareness',
  pass_power: 'Pass Power',
  pass_rush_deflection: 'Pass Rush Defl',
  quickness: 'Quickness',
  balance: 'Balance',
  vertical: 'Vertical',
  pass_carry_power: 'Drop Back Power',
  punt_accuracy: 'Punt Accuracy',
  hold_ground: 'Hold Ground',
  kickoff_power: 'Kickoff Power',
  pass_awareness: 'Pass Awareness',
  blitz_awareness: 'Blitz Awr',
  carry_power: 'Power Running',
  pass_block_power: 'Pass Blk Power',
  catch_awareness: 'Rec Awareness',
  kick_accuracy: 'Kick Accuracy',
  pass_grip: 'Drop Back Grip',
  run_block_technique: 'Run Blk Tech',
  heart: 'Heart',
  catch_in_traffic: 'Catch in Traffic',
  coverage_technique: 'Coverage Tech',
  lead_block_awareness: 'Lead Blk Awr',
  tackle_grip: 'Tackling Grip',
  sprinting: 'Sprinting',
  pass_rush_technique: 'Pass Rush Tech',
  coverage_deflection: 'Deflecting',
};

export const TRAIT_LOOKUP: Lookup = {
  dl_quick_reaction: 'Quick Reaction',
  active_hands: 'Active Hands',
  early_bloomer: 'Early Bloomer',
  k_cool_headed: 'Cool Headed',
  ball_hawk: 'Ball Hawk',
  high_jumper: 'High Jumper',
  grinder: 'Grinder',
  hb_power_rusher: 'Power Rusher',
  ol_tech_blocker: 'Technical Blocker',
  ol_run_blocker: 'Run Blocker',
  k_kickoff_king: 'Kickoff King',
  slippery: 'Slippery',
  ot_pass_protector: 'Pass Protector',
  jittery: 'Jittery',
  zone_specialist: 'Zone Specialist',
  ol_pass_blocker: 'Pass Blocker',
  fb_rusher: 'Rusher',
  wr_shifty: 'Shifty',
  strong_base: 'Strong Base',
  soft_hands: 'Soft Hands',
  dl_dreadnought: 'Dread-nought',
  ol_power_blocker: 'Power Blocker',
  qb_scrambler: 'Scrambler',
  fearsome: 'Fearsome',
  nerves_of_steel: 'Nerves of Steel',
  chasedown_artist: 'Chase Down Artist',
  lb_coverage: 'Coverage LB',
  adept: 'Adept',
  dl_juggernaut: 'Jugger NOT',
  enforcer: 'Enforcer',
  qb_precision_passer: 'Precision Passer',
  te_receiver: 'Receiving Specialist',
  spring_board: 'Spring Board',
  bruiser: 'Bruiser',
  qb_solid_frame: 'Solid Frame',
  qb_dual_threat: 'Dual Threat',
  dl_crusher: 'Crusher',
  egotist: 'Egotist',
  brick_wall: 'Brick Wall',
  dl_towering_man: 'Towering Man',
  prodigy: 'Prodigy',
  hidden_potential: 'Hidden Potential',
  qb_cool_headed: 'Cool Headed',
  d_anchor: 'D Anchor',
  tenacious: 'Tenacious',
  dl_run_stuffer: 'Run Stuffer',
  dl_technique_man: 'Technique Man',
  scholar: 'Scholar',
  fb_lead_blocker: 'Lead Blocker',
  workhorse: 'Workhorse',
  lb_middle_man: 'Middle Man',
  meathead: 'Meathead',
  hb_scat_back: 'Scat Back',
  k_sharpshooter: 'Sharp Shooter',
  wr_control: 'Dominator',
  fumble_creator: 'Fumble Creator',
  natural: 'Natural',
  unpredictable: 'Unpr-edic-table',
  c_quick_snap: 'Quick Snap',
  quick_feet: 'Quick Feet',
  qb_rusher: 'Rusher',
  return_specialist: 'Return Specialist',
  sure_tackler: 'Sure Tackler',
  ol_consistent_blocker: 'Consistent Blocker',
  wr_slot_receiver: 'Slot Receiver',
  qb_field_general: 'Field General',
  broad_jumper: 'Broad Jumper',
  hb_elusive_rusher: 'Elusive Rusher',
  playmaker: 'Playmaker',
  k_leg_of_steel: 'Leg of Steel',
  wr_speedster: 'Speedster',
  g_downfield_blocker: 'Downfield Blocker',
  qb_gunslinger: 'Gunslinger',
  hb_blocking_back: 'Blocking Back',
  qb_pocket_passer: 'Pocket Passer',
  superstar_nonglam: 'Superstar',
  superstar_avg: 'Superstar',
  p_sure_hands: 'Sure Hands',
  hb_rushing_back: 'Rusher',
  superstar_glam: 'Superstar',
  hb_unpredictable: 'Unpredictable',
  lightning_reflexes: 'Lightning Reflexes',
  fb_scat_back: 'Scat Back',
  dl_pass_rusher: 'Pass Rusher',
  thick_skin: 'Thick Skin',
  long_reach: 'Long Reach',
  shutdown_defender: 'Shutdown Defender',
  lb_blitzer: 'Blitzer',
  te_blocker: 'Blocking Specialist',
  tactician: 'Tactician',
  flex_coverage: 'Flex Coverage',
  man_specialist: 'Man Specialist',
  cb_speedster: 'Speedster',
  dl_heavyweight: 'Heavy Weight',
  easy_going: 'Easy Going',
};

export const ABILITY_LOOKUP: Lookup = {
  hard_cut: 'Hard Cut',
  road_warrior: 'Road Warrior',
  pick_six: 'Pick Six',
  hail_mary: 'Hail Mary',
  shed_block: 'Shed Block',
  slot_machine: 'Slot Machine',
  quick_hitter: 'Quick Hitter',
  youre_next: "You're Next",
  grinder: 'Grinder',
  coverage_commander: 'Coverage Commander',
  spin_cycle: 'Spin Cycle',
  first_strike: 'First Strike',
  goal_line_back: 'Goal Line Back',
  shed_sack: 'Shed Sack',
  celebration: 'Celebration',
  surge: 'Surge',
  resolute: 'Resolute',
  seeing_red: 'Seeing Red',
  home_town_hero: 'Home Town Hero',
  tuck_and_run: 'Tuck and Run',
  pinned_deep: 'Pinned Deep',
  opportunist: 'Opportunist',
  returner_rush: 'Returner Rush',
  pump_fake: 'Pump Fake',
  thread_the_needle: 'Thread the Needle',
  sure_footed: 'Sure-footed',
  pancake_chef: 'Pancake Chef',
  on_the_run: 'On the Run',
  mr_reliable: 'Mr. Reliable',
  domineer: 'Domineer',
  zone_shark: 'Zone Shark',
  protect_the_lead: 'Protect the Lead',
  brick_wall: 'Brick Wall',
  line_crasher: 'Line Crasher',
  power_through: 'Power Through',
  brace_for_impact: 'Brace for Impact',
  trash_talk: 'Trash Talk',
  rough_cover: 'Rough Cover',
  iron_grip: 'Iron Grip',
  entrapment: 'Entrapment',
  goal_line_blocker: 'Goal Line Blocker',
  pull_specialist: 'Pull Specialist',
  three_and_out: 'Three and Out',
  beat_down: 'Beat Down',
  chip_shot: 'Chip Shot',
  clock_manager: 'Clock Manager',
  freight_train: 'Freight Train',
  stiff_arm: 'Stiff Arm',
  first_step: 'First Step',
  streaky: 'Streaky',
  strong_arm: 'Strong Arm',
  tunnel_vision: 'Tunnel Vision',
  leverage: 'Leverage',
  second_wind: 'Second Wind',
  quick_read: 'Quick Read',
  contain_expert: 'Contain Expert',
  follow_up: 'Follow Up',
  showboat: 'Showboat',
  spin: 'Spin',
  head_fake: 'Head Fake',
  monster_hit: 'Monster Hit',
  prime_time: 'Prime Time',
  eyes_on_the_prize: 'Eyes on the Prize',
  immovable_object: 'Immovable Object',
  sideline_bomb: 'Sideline Bomb',
  death_grip: 'Death Grip',
  laces_out: 'Laces Out',
  power_drive: 'Power Drive',
  yac_attack: 'YAC Attack',
  swat_down: 'Swat Down',
  chase_down: 'Cover Expert',
  third_down_stopper: 'Third Down Stopper',
  on_an_island: 'On an Island',
  get_low: 'Get Low',
  inspire_fear: 'Inspire Fear',
  hands_up: 'Hands Up',
  goal_line_stand: 'Goal Line Stand',
  unstoppable_force: 'Unstoppable Force',
  wide_load: 'Wide Load',
  closing_speed: 'Closing Speed',
  catch_in_stride: 'Catch in Stride',
  juke: 'Juke',
  absolute_unit: 'Absolute Unit',
};

export const ABILITY_MEDAL_LOOKUP: Lookup = {
  1: { label: 'Bronze', color: '#AF814B' },
  2: { label: 'Silver', color: 'silver' },
  3: { label: 'Gold', color: 'gold' },
};
