export const POSITION_DATA: { [key: string]: any } = {
  FS: {
    min_height: 68,
    max_height: 76,
    max_weight: 205,
    type: 'def',
    full_name: 'Free Safety',
    min_weight: 185,
    height_weight_modifier: 2,
  },
  TE: {
    min_height: 72,
    max_height: 80,
    max_weight: 260,
    type: 'off',
    full_name: 'Tight End',
    min_weight: 230,
    height_weight_modifier: 2,
  },
  HB: {
    min_height: 66,
    max_height: 76,
    max_weight: 220,
    type: 'off',
    full_name: 'Halfback',
    min_weight: 180,
    height_weight_modifier: 4,
  },
  CB: {
    min_height: 68,
    max_height: 75,
    max_weight: 200,
    type: 'def',
    full_name: 'Cornerback',
    min_weight: 170,
    height_weight_modifier: 2,
  },
  K: {
    min_height: 69,
    max_height: 77,
    max_weight: 220,
    type: 'off',
    full_name: 'Kicker',
    min_weight: 170,
    height_weight_modifier: 1,
  },
  FB: {
    min_height: 70,
    max_height: 76,
    max_weight: 250,
    type: 'off',
    full_name: 'Fullback',
    min_weight: 220,
    height_weight_modifier: 2,
  },
  LB: {
    min_height: 70,
    max_height: 78,
    max_weight: 250,
    type: 'def',
    full_name: 'Linebacker',
    min_weight: 220,
    height_weight_modifier: 2,
  },
  C: {
    min_height: 72,
    max_height: 78,
    max_weight: 300,
    type: 'off',
    full_name: 'Center',
    min_weight: 230,
    height_weight_modifier: 5,
  },
  SS: {
    min_height: 69,
    max_height: 77,
    max_weight: 225,
    type: 'def',
    full_name: 'Strong Safety',
    min_weight: 195,
    height_weight_modifier: 1,
  },
  DT: {
    min_height: 72,
    max_height: 80,
    max_weight: 300,
    type: 'def',
    full_name: 'Defensive Tackle',
    min_weight: 250,
    height_weight_modifier: 8,
  },
  DE: {
    min_height: 71,
    max_height: 80,
    max_weight: 280,
    type: 'def',
    full_name: 'Defensive End',
    min_weight: 240,
    height_weight_modifier: 5,
  },
  P: {
    min_height: 71,
    max_height: 77,
    max_weight: 230,
    type: 'def',
    full_name: 'Punter',
    min_weight: 180,
    height_weight_modifier: 4,
  },
  QB: {
    min_height: 70,
    max_height: 78,
    max_weight: 205,
    type: 'off',
    full_name: 'Quarterback',
    min_weight: 165,
    height_weight_modifier: 6,
  },
  G: {
    min_height: 74,
    max_height: 79,
    max_weight: 325,
    type: 'off',
    full_name: 'Guard',
    min_weight: 290,
    height_weight_modifier: 6,
  },
  OT: {
    min_height: 74,
    max_height: 81,
    max_weight: 320,
    type: 'off',
    full_name: 'Offensive Tackle',
    min_weight: 280,
    height_weight_modifier: 4,
  },
  WR: {
    min_height: 68,
    max_height: 78,
    max_weight: 205,
    type: 'off',
    full_name: 'Wide Receiver',
    min_weight: 165,
    height_weight_modifier: 3,
  },
};
