export interface Template {
  position: string;
  templateName: string;
  height: number;
  weight: number;
  strength: number;
  speed: number;
  agility: number;
  stamina: number;
  awareness: number;
  confidence: number;
  trait1: string;
  trait2: string;
  trait3: string;
  skills: { [key: string]: { [build: string]: number } };
  abilities: { [key: string]: { [build: string]: number } };
}

export const getTemplates = (position: string): Template[] => {
  const templates: Template[] = [
    // QB
    {
      position: 'QB',
      templateName: 'Standard Star',
      height: 78,
      weight: 253,
      strength: 1,
      speed: 1,
      agility: 10,
      stamina: 6,
      awareness: 7,
      confidence: 10,
      trait1: 'superstar_glam',
      trait2: 'qb_pocket_passer',
      trait3: 'early_bloomer',
      skills: {
        start: {
          pass_technique: 80.0,
          pass_accuracy: 50.0,
          pass_power: 30.0,
          pass_consistency: 80.0,
          pass_grip: 0.0,
          pass_evasiveness: 0.0,
          pass_carry_power: 0.0,
          pass_awareness: 30.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          conditioning: 40.0,
          toughness: 20.0,
          heart: 50.0,
          intimidation: 0.0,
          leadership: 50.0,
        },
        end: {
          pass_technique: 100.0,
          pass_accuracy: 90.0,
          pass_power: 60.0,
          pass_consistency: 100.0,
          pass_grip: 25.0,
          pass_evasiveness: 65.0,
          pass_carry_power: 0.0,
          pass_awareness: 40.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          balance: 50.0,
          footwork: 30.0,
          quickness: 0.0,
          sprinting: 0.0,
          conditioning: 50.0,
          toughness: 30.0,
          heart: 50.0,
          intimidation: 0.0,
          leadership: 80.0,
        },
      },
      abilities: {
        start: {
          thread_the_needle: 3,
        },
        end: {
          thread_the_needle: 3,
          sideline_bomb: 3,
          on_the_run: 3,
        },
      },
    },
    {
      position: 'QB',
      templateName: 'Standard Star 2',
      height: 78,
      weight: 222,
      strength: 2,
      speed: 1,
      agility: 10,
      stamina: 6,
      awareness: 6,
      confidence: 10,
      trait1: 'superstar_glam',
      trait2: 'qb_pocket_passer',
      trait3: 'early_bloomer',
      skills: {
        start: {
          pass_technique: 0.0,
          pass_accuracy: 0.0,
          pass_power: 0.0,
          pass_consistency: 0.0,
          pass_grip: 0.0,
          pass_evasiveness: 0.0,
          pass_carry_power: 0.0,
          pass_awareness: 0.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          heart: 0.0,
          intimidation: 0.0,
          leadership: 0.0,
        },
        end: {
          pass_technique: 95.0,
          pass_accuracy: 90.0,
          pass_power: 70.0,
          pass_consistency: 100.0,
          pass_grip: 28.0,
          pass_evasiveness: 60.0,
          pass_carry_power: 0.0,
          pass_awareness: 30.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          balance: 40.0,
          footwork: 30.0,
          quickness: 0.0,
          sprinting: 0.0,
          conditioning: 50.0,
          toughness: 30.0,
          heart: 60.0,
          intimidation: 0.0,
          leadership: 80.0,
        },
      },
      abilities: {
        start: {
          thread_the_needle: 3,
        },
        end: {
          thread_the_needle: 3,
          sideline_bomb: 3,
          home_town_hero: 2,
          road_warrior: 2,
        },
      },
    },
    {
      position: 'QB',
      templateName: 'High PA Star',
      height: 78,
      weight: 253,
      strength: 1,
      speed: 1,
      agility: 10,
      stamina: 3,
      awareness: 10,
      confidence: 10,
      trait1: 'superstar_glam',
      trait2: 'qb_pocket_passer',
      trait3: 'early_bloomer',
      skills: {
        start: {
          pass_technique: 0.0,
          pass_accuracy: 0.0,
          pass_power: 0.0,
          pass_consistency: 0.0,
          pass_grip: 0.0,
          pass_evasiveness: 0.0,
          pass_carry_power: 0.0,
          pass_awareness: 0.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          heart: 0.0,
          intimidation: 0.0,
          leadership: 0.0,
        },
        end: {
          pass_technique: 90.0,
          pass_accuracy: 90.0,
          pass_power: 50.0,
          pass_consistency: 90.0,
          pass_grip: 30.0,
          pass_evasiveness: 50.0,
          pass_carry_power: 0.0,
          pass_awareness: 90.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          balance: 40.0,
          footwork: 30.0,
          quickness: 0.0,
          sprinting: 0.0,
          conditioning: 50.0,
          toughness: 30.0,
          heart: 50.0,
          intimidation: 0.0,
          leadership: 80.0,
        },
      },
      abilities: {
        start: {},
        end: {
          thread_the_needle: 3,
          quick_hitter: 3,
          quick_read: 2,
          sideline_bomb: 2,
        },
      },
    },
    {
      position: 'QB',
      templateName: 'Standard Prod',
      height: 78,
      weight: 222,
      strength: 2,
      speed: 1,
      agility: 10,
      stamina: 6,
      awareness: 6,
      confidence: 10,
      trait1: 'prodigy',
      trait2: 'qb_pocket_passer',
      trait3: 'early_bloomer',
      skills: {
        start: {
          pass_technique: 0.0,
          pass_accuracy: 0.0,
          pass_power: 0.0,
          pass_consistency: 0.0,
          pass_grip: 0.0,
          pass_evasiveness: 0.0,
          pass_carry_power: 0.0,
          pass_awareness: 0.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          heart: 0.0,
          intimidation: 0.0,
          leadership: 0.0,
        },
        end: {
          pass_technique: 90.0,
          pass_accuracy: 80.0,
          pass_power: 60.0,
          pass_consistency: 95.0,
          pass_grip: 30.0,
          pass_evasiveness: 50.0,
          pass_carry_power: 0.0,
          pass_awareness: 40.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          balance: 40.0,
          footwork: 30.0,
          quickness: 0.0,
          sprinting: 0.0,
          conditioning: 50.0,
          toughness: 30.0,
          heart: 50.0,
          intimidation: 0.0,
          leadership: 80.0,
        },
      },
      abilities: {
        start: {
          thread_the_needle: 2,
        },
        end: {
          thread_the_needle: 3,
          sideline_bomb: 3,
          clock_manager: 2,
        },
      },
    },
    {
      position: 'QB',
      templateName: 'Standard Normie',
      height: 78,
      weight: 253,
      strength: 4,
      speed: 1,
      agility: 10,
      stamina: 3,
      awareness: 7,
      confidence: 10,
      trait1: 'qb_pocket_passer',
      trait2: 'workhorse',
      trait3: 'early_bloomer',
      skills: {
        start: {
          pass_technique: 0.0,
          pass_accuracy: 0.0,
          pass_power: 0.0,
          pass_consistency: 0.0,
          pass_grip: 0.0,
          pass_evasiveness: 0.0,
          pass_carry_power: 0.0,
          pass_awareness: 0.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          heart: 0.0,
          intimidation: 0.0,
          leadership: 0.0,
        },
        end: {
          pass_technique: 90.0,
          pass_accuracy: 80.0,
          pass_power: 55.0,
          pass_consistency: 90.0,
          pass_grip: 20.0,
          pass_evasiveness: 50.0,
          pass_carry_power: 0.0,
          pass_awareness: 30.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          balance: 40.0,
          footwork: 30.0,
          quickness: 0.0,
          sprinting: 0.0,
          conditioning: 45.0,
          toughness: 30.0,
          heart: 50.0,
          intimidation: 0.0,
          leadership: 70.0,
        },
      },
      abilities: {
        start: {
          thread_the_needle: 2,
        },
        end: {
          thread_the_needle: 3,
          sideline_bomb: 3,
          second_wind: 2,
        },
      },
    },
    // FB
    {
      position: 'FB',
      templateName: 'Standard Normie',
      height: 70,
      weight: 220,
      strength: 8,
      speed: 8,
      agility: 10,
      stamina: 2,
      awareness: 4,
      confidence: 3,
      trait1: 'jittery',
      trait2: 'ol_tech_blocker',
      trait3: 'thick_skin',
      skills: {
        start: {
          pass_block_technique: 0.0,
          pass_block_power: 0.0,
          pass_block_awareness: 0.0,
          run_block_technique: 0.0,
          run_block_power: 0.0,
          run_block_awareness: 0.0,
          lead_block_awareness: 0.0,
          block_consistency: 0.0,
          route_technique: 0.0,
          route_elusiveness: 0.0,
          catch_hands: 0.0,
          catch_in_traffic: 0.0,
          catch_grip: 0.0,
          catch_awareness: 0.0,
          catch_consistency: 0.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          return_awareness: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          pass_block_technique: 0.0,
          pass_block_power: 0.0,
          pass_block_awareness: 0.0,
          run_block_technique: 53.0,
          run_block_power: 55.0,
          run_block_awareness: 50.0,
          lead_block_awareness: 60.0,
          block_consistency: 46.0,
          route_technique: 0.0,
          route_elusiveness: 0.0,
          catch_hands: 30.0,
          catch_in_traffic: 0.0,
          catch_grip: 3.0,
          catch_awareness: 0.0,
          catch_consistency: 0.0,
          carry_grip: 30.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          return_awareness: 0.0,
          balance: 70.0,
          footwork: 50.0,
          quickness: 60.0,
          sprinting: 69.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 71.0,
          toughness: 40.0,
          snap_reaction: 41.0,
          heart: 32.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {},
        end: {
          first_step: 3,
          pancake_chef: 3,
        },
      },
    },
    // HB
    {
      position: 'HB',
      templateName: 'Elusive',
      height: 66,
      weight: 180,
      strength: 1,
      speed: 8,
      agility: 10,
      stamina: 8,
      awareness: 7,
      confidence: 1,
      trait1: 'superstar_glam',
      trait2: 'egotist',
      trait3: 'hb_rushing_back',
      skills: {
        start: {
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          return_awareness: 0.0,
          route_technique: 0.0,
          route_elusiveness: 0.0,
          catch_hands: 0.0,
          catch_in_traffic: 0.0,
          catch_grip: 0.0,
          catch_awareness: 0.0,
          catch_consistency: 0.0,
          pass_block_technique: 0.0,
          pass_block_power: 0.0,
          pass_block_awareness: 0.0,
          run_block_technique: 0.0,
          run_block_power: 0.0,
          run_block_awareness: 0.0,
          lead_block_awareness: 0.0,
          block_consistency: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 90.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          carry_grip: 60.0,
          carry_power: 0.0,
          carry_elusiveness: 85.0,
          carry_awareness: 90.0,
          return_awareness: 0.0,
          route_technique: 0.0,
          route_elusiveness: 0.0,
          catch_hands: 0.0,
          catch_in_traffic: 0.0,
          catch_grip: 0.0,
          catch_awareness: 0.0,
          catch_consistency: 0.0,
          pass_block_technique: 0.0,
          pass_block_power: 0.0,
          pass_block_awareness: 0.0,
          run_block_technique: 0.0,
          run_block_power: 0.0,
          run_block_awareness: 0.0,
          lead_block_awareness: 0.0,
          block_consistency: 0.0,
          balance: 85.0,
          footwork: 70.0,
          quickness: 50.0,
          sprinting: 95.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 96.0,
          toughness: 40.0,
          snap_reaction: 0.0,
          heart: 35.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          juke: 3,
        },
        end: {
          juke: 3,
          sure_footed: 3,
          home_town_hero: 2,
          road_warrior: 2,
        },
      },
    },
    {
      position: 'HB',
      templateName: 'Power',
      height: 66,
      weight: 220,
      strength: 10,
      speed: 1,
      agility: 10,
      stamina: 10,
      awareness: 3,
      confidence: 1,
      trait1: 'superstar_glam',
      trait2: 'egotist',
      trait3: 'hb_rushing_back',
      skills: {
        start: {
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          return_awareness: 0.0,
          route_technique: 0.0,
          route_elusiveness: 0.0,
          catch_hands: 0.0,
          catch_in_traffic: 0.0,
          catch_grip: 0.0,
          catch_awareness: 0.0,
          catch_consistency: 0.0,
          pass_block_technique: 0.0,
          pass_block_power: 0.0,
          pass_block_awareness: 0.0,
          run_block_technique: 0.0,
          run_block_power: 0.0,
          run_block_awareness: 0.0,
          lead_block_awareness: 0.0,
          block_consistency: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 90.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          carry_grip: 80.0,
          carry_power: 100.0,
          carry_elusiveness: 0.0,
          carry_awareness: 80.0,
          return_awareness: 0.0,
          route_technique: 0.0,
          route_elusiveness: 0.0,
          catch_hands: 0.0,
          catch_in_traffic: 0.0,
          catch_grip: 0.0,
          catch_awareness: 0.0,
          catch_consistency: 0.0,
          pass_block_technique: 0.0,
          pass_block_power: 0.0,
          pass_block_awareness: 0.0,
          run_block_technique: 0.0,
          run_block_power: 0.0,
          run_block_awareness: 0.0,
          lead_block_awareness: 0.0,
          block_consistency: 0.0,
          balance: 95.0,
          footwork: 60.0,
          quickness: 50.0,
          sprinting: 60.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 100.0,
          toughness: 60.0,
          snap_reaction: 0.0,
          heart: 30.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          power_through: 3,
        },
        end: {
          power_through: 3,
          grinder: 3,
          home_town_hero: 2,
          road_warrior: 2,
        },
      },
    },
    {
      position: 'HB',
      templateName: 'Cerberus',
      height: 76,
      weight: 260,
      strength: 10,
      speed: 1,
      agility: 10,
      stamina: 10,
      awareness: 3,
      confidence: 1,
      trait1: 'superstar_glam',
      trait2: 'hb_rushing_back',
      trait3: 'unpredictable',
      skills: {
        start: {
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          return_awareness: 0.0,
          route_technique: 0.0,
          route_elusiveness: 0.0,
          catch_hands: 0.0,
          catch_in_traffic: 0.0,
          catch_grip: 0.0,
          catch_awareness: 0.0,
          catch_consistency: 0.0,
          pass_block_technique: 0.0,
          pass_block_power: 0.0,
          pass_block_awareness: 0.0,
          run_block_technique: 0.0,
          run_block_power: 0.0,
          run_block_awareness: 0.0,
          lead_block_awareness: 0.0,
          block_consistency: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 90.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          carry_grip: 60.0,
          carry_power: 95.0,
          carry_elusiveness: 80.0,
          carry_awareness: 80.0,
          return_awareness: 0.0,
          route_technique: 0.0,
          route_elusiveness: 0.0,
          catch_hands: 0.0,
          catch_in_traffic: 0.0,
          catch_grip: 0.0,
          catch_awareness: 0.0,
          catch_consistency: 0.0,
          pass_block_technique: 0.0,
          pass_block_power: 0.0,
          pass_block_awareness: 0.0,
          run_block_technique: 0.0,
          run_block_power: 0.0,
          run_block_awareness: 0.0,
          lead_block_awareness: 0.0,
          block_consistency: 0.0,
          balance: 100.0,
          footwork: 50.0,
          quickness: 40.0,
          sprinting: 40.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 100.0,
          toughness: 60.0,
          snap_reaction: 0.0,
          heart: 37.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          stiff_arm: 3,
        },
        end: {
          stiff_arm: 3,
          mr_reliable: 3,
          goal_line_back: 3,
        },
      },
    },
    {
      position: 'HB',
      templateName: 'Slombo',
      height: 66,
      weight: 188,
      strength: 10,
      speed: 1,
      agility: 10,
      stamina: 10,
      awareness: 3,
      confidence: 1,
      trait1: 'superstar_glam',
      trait2: 'hb_rushing_back',
      trait3: 'unpredictable',
      skills: {
        start: {
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          return_awareness: 0.0,
          route_technique: 0.0,
          route_elusiveness: 0.0,
          catch_hands: 0.0,
          catch_in_traffic: 0.0,
          catch_grip: 0.0,
          catch_awareness: 0.0,
          catch_consistency: 0.0,
          pass_block_technique: 0.0,
          pass_block_power: 0.0,
          pass_block_awareness: 0.0,
          run_block_technique: 0.0,
          run_block_power: 0.0,
          run_block_awareness: 0.0,
          lead_block_awareness: 0.0,
          block_consistency: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 90.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          carry_grip: 80.0,
          carry_power: 95.0,
          carry_elusiveness: 80.0,
          carry_awareness: 80.0,
          return_awareness: 0.0,
          route_technique: 0.0,
          route_elusiveness: 0.0,
          catch_hands: 0.0,
          catch_in_traffic: 0.0,
          catch_grip: 0.0,
          catch_awareness: 0.0,
          catch_consistency: 0.0,
          pass_block_technique: 0.0,
          pass_block_power: 0.0,
          pass_block_awareness: 0.0,
          run_block_technique: 0.0,
          run_block_power: 0.0,
          run_block_awareness: 0.0,
          lead_block_awareness: 0.0,
          block_consistency: 0.0,
          balance: 80.0,
          footwork: 75.0,
          quickness: 40.0,
          sprinting: 40.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 96.0,
          toughness: 40.0,
          snap_reaction: 0.0,
          heart: 30.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          stiff_arm: 3,
        },
        end: {
          stiff_arm: 3,
          spin: 3,
          home_town_hero: 2,
          road_warrior: 2,
        },
      },
    },
    // TE
    {
      position: 'TE',
      templateName: 'Standard Star',
      height: 80,
      weight: 246,
      strength: 1,
      speed: 1,
      agility: 5,
      stamina: 8,
      awareness: 10,
      confidence: 10,
      trait1: 'superstar_glam',
      trait2: 'natural',
      trait3: 'hidden_potential',
      skills: {
        start: {
          route_technique: 0.0,
          route_elusiveness: 0.0,
          catch_hands: 0.0,
          catch_in_traffic: 0.0,
          catch_grip: 0.0,
          catch_awareness: 0.0,
          catch_consistency: 0.0,
          pass_block_technique: 0.0,
          pass_block_power: 0.0,
          pass_block_awareness: 0.0,
          run_block_technique: 0.0,
          run_block_power: 0.0,
          run_block_awareness: 0.0,
          lead_block_awareness: 0.0,
          block_consistency: 0.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          return_awareness: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          route_technique: 80.0,
          route_elusiveness: 65.0,
          catch_hands: 75.0,
          catch_in_traffic: 90.0,
          catch_grip: 45.0,
          catch_awareness: 50.0,
          catch_consistency: 90.0,
          pass_block_technique: 0.0,
          pass_block_power: 0.0,
          pass_block_awareness: 0.0,
          run_block_technique: 0.0,
          run_block_power: 0.0,
          run_block_awareness: 0.0,
          lead_block_awareness: 0.0,
          block_consistency: 0.0,
          carry_grip: 30.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          return_awareness: 0.0,
          balance: 50.0,
          footwork: 30.0,
          quickness: 45.0,
          sprinting: 84.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 90.0,
          toughness: 40,
          snap_reaction: 75.0,
          heart: 45.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {},
        end: {
          head_fake: 3,
          hard_cut: 3,
          prime_time: 3,
        },
      },
    },
    // WR
    {
      position: 'WR',
      templateName: 'Standard Normie',
      height: 78,
      weight: 196,
      strength: 1,
      speed: 2,
      agility: 8,
      stamina: 6,
      awareness: 8,
      confidence: 10,
      trait1: 'natural',
      trait2: 'hidden_potential',
      trait3: 'workhorse',
      skills: {
        start: {
          route_technique: 0.0,
          route_elusiveness: 0.0,
          catch_hands: 0.0,
          catch_in_traffic: 0.0,
          catch_grip: 0.0,
          catch_awareness: 0.0,
          catch_consistency: 0.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          return_awareness: 0.0,
          run_block_technique: 0.0,
          run_block_power: 0.0,
          run_block_awareness: 0.0,
          block_consistency: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          route_technique: 70.0,
          route_elusiveness: 70.0,
          catch_hands: 70.0,
          catch_in_traffic: 85.0,
          catch_grip: 30.0,
          catch_awareness: 50.0,
          catch_consistency: 90.0,
          carry_grip: 30.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          carry_awareness: 0.0,
          return_awareness: 0.0,
          run_block_technique: 0.0,
          run_block_power: 0.0,
          run_block_awareness: 0.0,
          block_consistency: 0.0,
          balance: 50.0,
          footwork: 30.0,
          quickness: 50.0,
          sprinting: 70.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 75.0,
          toughness: 30.0,
          snap_reaction: 60.0,
          heart: 40.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {},
        end: {
          head_fake: 3,
          hard_cut: 3,
          prime_time: 2,
        },
      },
    },
    // DT
    {
      position: 'DT',
      templateName: 'Spin Star',
      height: 72,
      weight: 250,
      strength: 1,
      speed: 1,
      agility: 10,
      stamina: 7,
      awareness: 10,
      confidence: 6,
      trait1: 'superstar_nonglam',
      trait2: 'natural',
      trait3: 'dl_technique_man',
      skills: {
        start: {
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          break_run_block: 0.0,
          blitz_awareness: 0.0,
          hold_ground: 0.0,
          tackle_awareness: 0.0,
          defense_consistency: 0.0,
          tackle_technique: 0.0,
          tackle_power: 0.0,
          tackle_strip: 0.0,
          tackle_grip: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          pass_rush_technique: 99.0,
          pass_rush_power: 30.0,
          pass_rush_deflection: 0.0,
          break_run_block: 100.0,
          blitz_awareness: 70.0,
          hold_ground: 65.0,
          tackle_awareness: 50.0,
          defense_consistency: 50.0,
          tackle_technique: 50.0,
          tackle_power: 40.0,
          tackle_strip: 0.0,
          tackle_grip: 50.0,
          balance: 70.0,
          footwork: 60.0,
          quickness: 45.0,
          sprinting: 40.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 65.0,
          toughness: 80.0,
          snap_reaction: 100.0,
          heart: 40.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          spin_cycle: 3,
        },
        end: {
          spin_cycle: 3,
          shed_block: 3,
          first_strike: 3,
        },
      },
    },
    {
      position: 'DT',
      templateName: 'Spin Normie',
      height: 72,
      weight: 250,
      strength: 1,
      speed: 1,
      agility: 10,
      stamina: 5,
      awareness: 10,
      confidence: 8,
      trait1: 'dl_technique_man',
      trait2: 'jittery',
      trait3: 'thick_skin',
      skills: {
        start: {
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          break_run_block: 0.0,
          blitz_awareness: 0.0,
          hold_ground: 0.0,
          tackle_awareness: 0.0,
          defense_consistency: 0.0,
          tackle_technique: 0.0,
          tackle_power: 0.0,
          tackle_strip: 0.0,
          tackle_grip: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          pass_rush_technique: 80.0,
          pass_rush_power: 30.0,
          pass_rush_deflection: 0.0,
          break_run_block: 90.0,
          blitz_awareness: 60.0,
          hold_ground: 60.0,
          tackle_awareness: 50.0,
          defense_consistency: 50.0,
          tackle_technique: 40.0,
          tackle_power: 40.0,
          tackle_strip: 0.0,
          tackle_grip: 40.0,
          balance: 70.0,
          footwork: 50.0,
          quickness: 30.0,
          sprinting: 30.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 60.0,
          toughness: 80.0,
          snap_reaction: 100.0,
          heart: 40.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          spin_cycle: 2,
        },
        end: {
          spin_cycle: 3,
          shed_block: 3,
          showboat: 2,
        },
      },
    },
    // DE
    {
      position: 'DE',
      templateName: 'Spin Star',
      height: 72,
      weight: 245,
      strength: 1,
      speed: 1,
      agility: 10,
      stamina: 5,
      awareness: 10,
      confidence: 8,
      trait1: 'superstar_nonglam',
      trait2: 'natural',
      trait3: 'dl_technique_man',
      skills: {
        start: {
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          break_run_block: 0.0,
          blitz_awareness: 0.0,
          hold_ground: 0.0,
          tackle_awareness: 0.0,
          defense_consistency: 0.0,
          zone_coverage_awareness: 0.0,
          coverage_deflection: 0.0,
          coverage_interception: 0.0,
          tackle_technique: 0.0,
          tackle_power: 0.0,
          tackle_strip: 0.0,
          tackle_grip: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          pass_rush_technique: 100.0,
          pass_rush_power: 30.0,
          pass_rush_deflection: 0.0,
          break_run_block: 100.0,
          blitz_awareness: 80.0,
          hold_ground: 65.0,
          tackle_awareness: 50.0,
          defense_consistency: 60.0,
          zone_coverage_awareness: 0.0,
          coverage_deflection: 0.0,
          coverage_interception: 0.0,
          tackle_technique: 50.0,
          tackle_power: 40.0,
          tackle_strip: 0.0,
          tackle_grip: 50.0,
          balance: 70.0,
          footwork: 60.0,
          quickness: 45.0,
          sprinting: 40.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 65.0,
          toughness: 80.0,
          snap_reaction: 100.0,
          heart: 40.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          spin_cycle: 3,
        },
        end: {
          spin_cycle: 3,
          shed_block: 3,
          first_strike: 3,
        },
      },
    },
    {
      position: 'DE',
      templateName: 'Spin Normie',
      height: 71,
      weight: 240,
      strength: 1,
      speed: 1,
      agility: 10,
      stamina: 3,
      awareness: 10,
      confidence: 10,
      trait1: 'dl_technique_man',
      trait2: 'jittery',
      trait3: 'thick_skin',
      skills: {
        start: {
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          break_run_block: 0.0,
          blitz_awareness: 0.0,
          hold_ground: 0.0,
          tackle_awareness: 0.0,
          defense_consistency: 0.0,
          zone_coverage_awareness: 0.0,
          coverage_deflection: 0.0,
          coverage_interception: 0.0,
          tackle_technique: 0.0,
          tackle_power: 0.0,
          tackle_strip: 0.0,
          tackle_grip: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          pass_rush_technique: 90.0,
          pass_rush_power: 30.0,
          pass_rush_deflection: 0.0,
          break_run_block: 90.0,
          blitz_awareness: 60.0,
          hold_ground: 50.0,
          tackle_awareness: 40.0,
          defense_consistency: 50.0,
          zone_coverage_awareness: 0.0,
          coverage_deflection: 0.0,
          coverage_interception: 0.0,
          tackle_technique: 40.0,
          tackle_power: 40.0,
          tackle_strip: 0.0,
          tackle_grip: 40.0,
          balance: 70.0,
          footwork: 60.0,
          quickness: 30.0,
          sprinting: 30.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 60.0,
          toughness: 75.0,
          snap_reaction: 90.0,
          heart: 40.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          spin_cycle: 2,
        },
        end: {
          spin_cycle: 3,
          shed_block: 3,
          showboat: 2,
        },
      },
    },
    // LB
    {
      position: 'LB',
      templateName: 'Standard Man Star',
      height: 78,
      weight: 238,
      strength: 1,
      speed: 5,
      agility: 10,
      stamina: 6,
      awareness: 10,
      confidence: 3,
      trait1: 'superstar_glam',
      trait2: 'natural',
      trait3: 'workhorse',
      skills: {
        start: {
          tackle_technique: 70.0,
          tackle_power: 50.0,
          tackle_strip: 40.0,
          tackle_grip: 40.0,
          break_run_block: 30.0,
          blitz_awareness: 0.0,
          hold_ground: 20.0,
          tackle_awareness: 80.0,
          defense_consistency: 40.0,
          man_coverage_awareness: 80.0,
          zone_coverage_awareness: 0.0,
          coverage_technique: 40.0,
          coverage_deflection: 40.0,
          coverage_interception: 0.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          balance: 50.0,
          footwork: 35.0,
          quickness: 35.0,
          sprinting: 45.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 65.0,
          toughness: 30.0,
          snap_reaction: 0.0,
          heart: 34.0,
          intimidation: 0.0,
        },
        end: {
          tackle_technique: 85.0,
          tackle_power: 70.0,
          tackle_strip: 40.0,
          tackle_grip: 50.0,
          break_run_block: 70.0,
          blitz_awareness: 0.0,
          hold_ground: 30.0,
          tackle_awareness: 85.0,
          defense_consistency: 60.0,
          man_coverage_awareness: 90.0,
          zone_coverage_awareness: 0.0,
          coverage_technique: 60.0,
          coverage_deflection: 70.0,
          coverage_interception: 30.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          balance: 65.0,
          footwork: 50.0,
          quickness: 50.0,
          sprinting: 75.0,
          vertical: 0.0,
          diving: 30.0,
          conditioning: 80.0,
          toughness: 40.0,
          snap_reaction: 40.0,
          heart: 40.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          shed_block: 3,
        },
        end: {
          monster_hit: 3,
          chase_down: 3,
          shed_block: 3,
        },
      },
    },
    {
      position: 'LB',
      templateName: 'Standard Zone Star',
      height: 78,
      weight: 238,
      strength: 1,
      speed: 5,
      agility: 10,
      stamina: 6,
      awareness: 10,
      confidence: 3,
      trait1: 'superstar_glam',
      trait2: 'natural',
      trait3: 'workhorse',
      skills: {
        start: {
          tackle_technique: 75.0,
          tackle_power: 50.0,
          tackle_strip: 40.0,
          tackle_grip: 40.0,
          break_run_block: 30.0,
          blitz_awareness: 0.0,
          hold_ground: 25.0,
          tackle_awareness: 80.0,
          defense_consistency: 40.0,
          man_coverage_awareness: 0.0,
          zone_coverage_awareness: 90.0,
          coverage_technique: 35.0,
          coverage_deflection: 40.0,
          coverage_interception: 20.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          balance: 50.0,
          footwork: 40.0,
          quickness: 35.0,
          sprinting: 40.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 65.0,
          toughness: 30.0,
          snap_reaction: 0.0,
          heart: 30.0,
          intimidation: 0.0,
        },
        end: {
          tackle_technique: 80.0,
          tackle_power: 70.0,
          tackle_strip: 40.0,
          tackle_grip: 50.0,
          break_run_block: 50.0,
          blitz_awareness: 0.0,
          hold_ground: 30.0,
          tackle_awareness: 85.0,
          defense_consistency: 60.0,
          man_coverage_awareness: 0.0,
          zone_coverage_awareness: 100.0,
          coverage_technique: 70.0,
          coverage_deflection: 75.0,
          coverage_interception: 40.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          balance: 65.0,
          footwork: 55.0,
          quickness: 50.0,
          sprinting: 70.0,
          vertical: 30.0,
          diving: 30.0,
          conditioning: 85.0,
          toughness: 40.0,
          snap_reaction: 0.0,
          heart: 40.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          zone_shark: 3,
        },
        end: {
          monster_hit: 3,
          chase_down: 3,
          zone_shark: 3,
        },
      },
    },
    {
      position: 'LB',
      templateName: 'Standard Man Normie',
      height: 78,
      weight: 236,
      strength: 1,
      speed: 8,
      agility: 9,
      stamina: 4,
      awareness: 10,
      confidence: 3,
      trait1: 'natural',
      trait2: 'chasedown_artist',
      trait3: 'long_reach',
      skills: {
        start: {
          tackle_technique: 55.0,
          tackle_power: 50.0,
          tackle_strip: 30.0,
          tackle_grip: 25.0,
          break_run_block: 30.0,
          blitz_awareness: 0.0,
          hold_ground: 0.0,
          tackle_awareness: 80.0,
          defense_consistency: 35.0,
          man_coverage_awareness: 74.0,
          zone_coverage_awareness: 0.0,
          coverage_technique: 30.0,
          coverage_deflection: 30.0,
          coverage_interception: 0.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          balance: 45.0,
          footwork: 35.0,
          quickness: 30.0,
          sprinting: 40.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 55.0,
          toughness: 30.0,
          snap_reaction: 0.0,
          heart: 30.0,
          intimidation: 0.0,
        },
        end: {
          tackle_technique: 80.0,
          tackle_power: 57.0,
          tackle_strip: 40.0,
          tackle_grip: 40.0,
          break_run_block: 40.0,
          blitz_awareness: 0.0,
          hold_ground: 20.0,
          tackle_awareness: 80.0,
          defense_consistency: 42.0,
          man_coverage_awareness: 85.0,
          zone_coverage_awareness: 0.0,
          coverage_technique: 60.0,
          coverage_deflection: 65.0,
          coverage_interception: 20.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          balance: 65.0,
          footwork: 40.0,
          quickness: 50.0,
          sprinting: 70.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 71.0,
          toughness: 40.0,
          snap_reaction: 40.0,
          heart: 40.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          chase_down: 2,
        },
        end: {
          on_an_island: 3,
          chase_down: 3,
        },
      },
    },
    {
      position: 'LB',
      templateName: 'Standard Zone Normie',
      height: 78,
      weight: 236,
      strength: 1,
      speed: 8,
      agility: 10,
      stamina: 1,
      awareness: 10,
      confidence: 5,
      trait1: 'natural',
      trait2: 'chasedown_artist',
      trait3: 'workhorse',
      skills: {
        start: {
          tackle_technique: 50.0,
          tackle_power: 50.0,
          tackle_strip: 30.0,
          tackle_grip: 40.0,
          break_run_block: 30.0,
          blitz_awareness: 0.0,
          hold_ground: 25.0,
          tackle_awareness: 80.0,
          defense_consistency: 40.0,
          man_coverage_awareness: 0.0,
          zone_coverage_awareness: 85.0,
          coverage_technique: 30.0,
          coverage_deflection: 30.0,
          coverage_interception: 0.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          balance: 45.0,
          footwork: 30.0,
          quickness: 30.0,
          sprinting: 35.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 57.0,
          toughness: 30.0,
          snap_reaction: 0.0,
          heart: 30.0,
          intimidation: 0.0,
        },
        end: {
          tackle_technique: 80.0,
          tackle_power: 50.0,
          tackle_strip: 40.0,
          tackle_grip: 50.0,
          break_run_block: 50.0,
          blitz_awareness: 0.0,
          hold_ground: 30.0,
          tackle_awareness: 84.0,
          defense_consistency: 50.0,
          man_coverage_awareness: 0.0,
          zone_coverage_awareness: 93.0,
          coverage_technique: 47.0,
          coverage_deflection: 50.0,
          coverage_interception: 40.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          balance: 60.0,
          footwork: 50.0,
          quickness: 45.0,
          sprinting: 70.0,
          vertical: 30.0,
          diving: 0.0,
          conditioning: 71.0,
          toughness: 40.0,
          snap_reaction: 0.0,
          heart: 40.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          zone_shark: 2,
        },
        end: {
          zone_shark: 3,
          chase_down: 3,
          contain_expert: 2,
        },
      },
    },
    // CB
    {
      position: 'CB',
      templateName: 'Standard Man Star',
      height: 75,
      weight: 184,
      strength: 1,
      speed: 1,
      agility: 10,
      stamina: 7,
      awareness: 10,
      confidence: 6,
      trait1: 'superstar_avg',
      trait2: 'natural',
      trait3: 'egotist',
      skills: {
        start: {
          man_coverage_awareness: 0.0,
          zone_coverage_awareness: 0.0,
          coverage_technique: 0.0,
          coverage_deflection: 0.0,
          coverage_interception: 0.0,
          tackle_technique: 0.0,
          tackle_power: 0.0,
          tackle_strip: 0.0,
          tackle_grip: 0.0,
          break_run_block: 0.0,
          blitz_awareness: 0.0,
          hold_ground: 0.0,
          tackle_awareness: 0.0,
          defense_consistency: 0.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          return_awareness: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          man_coverage_awareness: 100.0,
          zone_coverage_awareness: 0.0,
          coverage_technique: 85.0,
          coverage_deflection: 90.0,
          coverage_interception: 40.0,
          tackle_technique: 60.0,
          tackle_power: 40.0,
          tackle_strip: 40.0,
          tackle_grip: 50.0,
          break_run_block: 40.0,
          blitz_awareness: 0.0,
          hold_ground: 30.0,
          tackle_awareness: 50.0,
          defense_consistency: 70.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          return_awareness: 0.0,
          balance: 65.0,
          footwork: 60.0,
          quickness: 60.0,
          sprinting: 80.0,
          vertical: 0.0,
          diving: 30.0,
          conditioning: 85.0,
          toughness: 45.0,
          snap_reaction: 40.0,
          heart: 40.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {},
        end: {
          on_an_island: 3,
          swat_down: 3,
          chase_down: 3,
        },
      },
    },
    {
      position: 'CB',
      templateName: 'Standard Zone Star',
      height: 75,
      weight: 184,
      strength: 1,
      speed: 1,
      agility: 10,
      stamina: 8,
      awareness: 10,
      confidence: 5,
      trait1: 'superstar_avg',
      trait2: 'natural',
      trait3: 'cb_speedster',
      skills: {
        start: {
          man_coverage_awareness: 0.0,
          zone_coverage_awareness: 0.0,
          coverage_technique: 0.0,
          coverage_deflection: 0.0,
          coverage_interception: 0.0,
          tackle_technique: 0.0,
          tackle_power: 0.0,
          tackle_strip: 0.0,
          tackle_grip: 0.0,
          break_run_block: 0.0,
          blitz_awareness: 0.0,
          hold_ground: 0.0,
          tackle_awareness: 0.0,
          defense_consistency: 0.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          return_awareness: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          man_coverage_awareness: 0.0,
          zone_coverage_awareness: 100.0,
          coverage_technique: 80.0,
          coverage_deflection: 90.0,
          coverage_interception: 40.0,
          tackle_technique: 60.0,
          tackle_power: 40.0,
          tackle_strip: 40.0,
          tackle_grip: 50.0,
          break_run_block: 45.0,
          blitz_awareness: 0.0,
          hold_ground: 30.0,
          tackle_awareness: 50.0,
          defense_consistency: 60.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          return_awareness: 0.0,
          balance: 70.0,
          footwork: 60.0,
          quickness: 60.0,
          sprinting: 82.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 85.0,
          toughness: 30.0,
          snap_reaction: 40.0,
          heart: 40.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          eyes_on_the_prize: 3,
        },
        end: {
          eyes_on_the_prize: 3,
          zone_shark: 3,
          chase_down: 3,
        },
      },
    },
    {
      position: 'CB',
      templateName: 'Standard Zone Normie',
      height: 68,
      weight: 170,
      strength: 1,
      speed: 8,
      agility: 9,
      stamina: 1,
      awareness: 10,
      confidence: 6,
      trait1: 'natural',
      trait2: 'chasedown_artist',
      trait3: 'thick_skin',
      skills: {
        start: {
          man_coverage_awareness: 0.0,
          zone_coverage_awareness: 0.0,
          coverage_technique: 0.0,
          coverage_deflection: 0.0,
          coverage_interception: 0.0,
          tackle_technique: 0.0,
          tackle_power: 0.0,
          tackle_strip: 0.0,
          tackle_grip: 0.0,
          break_run_block: 0.0,
          blitz_awareness: 0.0,
          hold_ground: 0.0,
          tackle_awareness: 0.0,
          defense_consistency: 0.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          return_awareness: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          man_coverage_awareness: 0.0,
          zone_coverage_awareness: 94.0,
          coverage_technique: 70.0,
          coverage_deflection: 70.0,
          coverage_interception: 40.0,
          tackle_technique: 50.0,
          tackle_power: 30.0,
          tackle_strip: 40.0,
          tackle_grip: 40.0,
          break_run_block: 40.0,
          blitz_awareness: 0.0,
          hold_ground: 30.0,
          tackle_awareness: 50.0,
          defense_consistency: 50.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          return_awareness: 0.0,
          balance: 65.0,
          footwork: 60.0,
          quickness: 50.0,
          sprinting: 75.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 70.0,
          toughness: 30.0,
          snap_reaction: 25.0,
          heart: 40.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          eyes_on_the_prize: 3,
        },
        end: {
          eyes_on_the_prize: 3,
          chase_down: 3,
          contain_expert: 2,
        },
      },
    },
    {
      position: 'CB',
      templateName: 'Standard Man Normie',
      height: 68,
      weight: 170,
      strength: 1,
      speed: 3,
      agility: 10,
      stamina: 1,
      awareness: 10,
      confidence: 10,
      trait1: 'hidden_potential',
      trait2: 'chasedown_artist',
      trait3: 'long_reach',
      skills: {
        start: {
          man_coverage_awareness: 0.0,
          zone_coverage_awareness: 0.0,
          coverage_technique: 0.0,
          coverage_deflection: 0.0,
          coverage_interception: 0.0,
          tackle_technique: 0.0,
          tackle_power: 0.0,
          tackle_strip: 0.0,
          tackle_grip: 0.0,
          break_run_block: 0.0,
          blitz_awareness: 0.0,
          hold_ground: 0.0,
          tackle_awareness: 0.0,
          defense_consistency: 0.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          return_awareness: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          man_coverage_awareness: 100.0,
          zone_coverage_awareness: 0.0,
          coverage_technique: 60.0,
          coverage_deflection: 80.0,
          coverage_interception: 30.0,
          tackle_technique: 40.0,
          tackle_power: 30.0,
          tackle_strip: 40.0,
          tackle_grip: 40.0,
          break_run_block: 40.0,
          blitz_awareness: 0.0,
          hold_ground: 20.0,
          tackle_awareness: 50.0,
          defense_consistency: 60.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          carry_grip: 0.0,
          carry_power: 0.0,
          carry_elusiveness: 0.0,
          return_awareness: 0.0,
          balance: 65.0,
          footwork: 60.0,
          quickness: 60.0,
          sprinting: 67.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 74.0,
          toughness: 50.0,
          snap_reaction: 30.0,
          heart: 40.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          swat_down: 3,
        },
        end: {
          swat_down: 3,
          chase_down: 3,
          third_down_stopper: 2,
        },
      },
    },
    // FS
    {
      position: 'FS',
      templateName: 'Standard Man Star',
      height: 76,
      weight: 201,
      strength: 1,
      speed: 7,
      agility: 9,
      stamina: 2,
      awareness: 10,
      confidence: 6,
      trait1: 'superstar_avg',
      trait2: 'natural',
      trait3: 'workhorse',
      skills: {
        start: {
          man_coverage_awareness: 0.0,
          zone_coverage_awareness: 0.0,
          coverage_technique: 0.0,
          coverage_deflection: 0.0,
          coverage_interception: 0.0,
          tackle_technique: 0.0,
          tackle_power: 0.0,
          tackle_strip: 0.0,
          tackle_grip: 0.0,
          break_run_block: 0.0,
          blitz_awareness: 0.0,
          hold_ground: 0.0,
          tackle_awareness: 0.0,
          defense_consistency: 0.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          return_awareness: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          man_coverage_awareness: 95.0,
          zone_coverage_awareness: 0.0,
          coverage_technique: 80.0,
          coverage_deflection: 80.0,
          coverage_interception: 0.0,
          tackle_technique: 80.0,
          tackle_power: 60.0,
          tackle_strip: 40.0,
          tackle_grip: 50.0,
          break_run_block: 0.0,
          blitz_awareness: 0.0,
          hold_ground: 0.0,
          tackle_awareness: 90.0,
          defense_consistency: 65.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          return_awareness: 0.0,
          balance: 65.0,
          footwork: 60.0,
          quickness: 55.0,
          sprinting: 80.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 85.0,
          toughness: 40.0,
          snap_reaction: 40.0,
          heart: 40.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {},
        end: {
          on_an_island: 3,
          swat_down: 3,
          chase_down: 3,
        },
      },
    },
    {
      position: 'FS',
      templateName: 'Standard Zone Star',
      height: 75,
      weight: 199,
      strength: 1,
      speed: 6,
      agility: 10,
      stamina: 1,
      awareness: 10,
      confidence: 7,
      trait1: 'superstar_avg',
      trait2: 'natural',
      trait3: 'hidden_potential',
      skills: {
        start: {
          man_coverage_awareness: 0.0,
          zone_coverage_awareness: 0.0,
          coverage_technique: 0.0,
          coverage_deflection: 0.0,
          coverage_interception: 0.0,
          tackle_technique: 0.0,
          tackle_power: 0.0,
          tackle_strip: 0.0,
          tackle_grip: 0.0,
          break_run_block: 0.0,
          blitz_awareness: 0.0,
          hold_ground: 0.0,
          tackle_awareness: 0.0,
          defense_consistency: 0.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          return_awareness: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          man_coverage_awareness: 0.0,
          zone_coverage_awareness: 100.0,
          coverage_technique: 75.0,
          coverage_deflection: 80.0,
          coverage_interception: 30.0,
          tackle_technique: 86.0,
          tackle_power: 61.0,
          tackle_strip: 40.0,
          tackle_grip: 50.0,
          break_run_block: 0.0,
          blitz_awareness: 20.0,
          hold_ground: 0.0,
          tackle_awareness: 95.0,
          defense_consistency: 70.0,
          pass_rush_technique: 0.0,
          pass_rush_power: 0.0,
          pass_rush_deflection: 0.0,
          return_awareness: 0.0,
          balance: 65.0,
          footwork: 60.0,
          quickness: 50.0,
          sprinting: 85.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 85.0,
          toughness: 30.0,
          snap_reaction: 0.0,
          heart: 40.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {},
        end: {
          monster_hit: 3,
          zone_shark: 3,
          chase_down: 3,
        },
      },
    },
    // C
    {
      position: 'C',
      templateName: 'Starter Normie',
      height: 78,
      weight: 320,
      strength: 5,
      speed: 1,
      agility: 10,
      stamina: 6,
      awareness: 4,
      confidence: 9,
      trait1: 'ol_tech_blocker',
      trait2: 'early_bloomer',
      trait3: 'thick_skin',
      skills: {
        start: {
          pass_block_technique: 30.0,
          pass_block_power: 30.0,
          pass_block_awareness: 20.0,
          run_block_technique: 60.0,
          run_block_power: 30.0,
          run_block_awareness: 30.0,
          block_consistency: 35.0,
          balance: 60.0,
          footwork: 25.0,
          quickness: 15.0,
          sprinting: 15.0,
          conditioning: 55.0,
          toughness: 65.0,
          snap_reaction: 25.0,
          heart: 35.0,
          intimidation: 0.0,
        },
        end: {
          pass_block_technique: 50.0,
          pass_block_power: 30.0,
          pass_block_awareness: 30.0,
          run_block_technique: 85.0,
          run_block_power: 50.0,
          run_block_awareness: 40.0,
          block_consistency: 70.0,
          balance: 70.0,
          footwork: 30.0,
          quickness: 25.0,
          sprinting: 25.0,
          conditioning: 65.0,
          toughness: 80.0,
          snap_reaction: 45.0,
          heart: 50.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          pancake_chef: 2,
        },
        end: {
          leverage: 3,
          pancake_chef: 3,
          immovable_object: 2,
        },
      },
    },
    // G
    {
      position: 'G',
      templateName: 'Starter Normie',
      height: 78,
      weight: 320,
      strength: 3,
      speed: 1,
      agility: 10,
      stamina: 8,
      awareness: 4,
      confidence: 9,
      trait1: 'ol_tech_blocker',
      trait2: 'early_bloomer',
      trait3: 'thick_skin',
      skills: {
        start: {
          pass_block_technique: 30.0,
          pass_block_power: 30.0,
          pass_block_awareness: 20.0,
          run_block_technique: 60.0,
          run_block_power: 30.0,
          run_block_awareness: 30.0,
          lead_block_awareness: 20.0,
          block_consistency: 35.0,
          balance: 60.0,
          footwork: 25.0,
          quickness: 15.0,
          sprinting: 15.0,
          conditioning: 55.0,
          toughness: 70.0,
          snap_reaction: 30.0,
          heart: 35.0,
          intimidation: 0.0,
        },
        end: {
          pass_block_technique: 50.0,
          pass_block_power: 30.0,
          pass_block_awareness: 30.0,
          run_block_technique: 85.0,
          run_block_power: 50.0,
          run_block_awareness: 40.0,
          lead_block_awareness: 30.0,
          block_consistency: 70.0,
          balance: 70.0,
          footwork: 30.0,
          quickness: 25.0,
          sprinting: 25.0,
          conditioning: 65.0,
          toughness: 80.0,
          snap_reaction: 60.0,
          heart: 50.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          pancake_chef: 2,
        },
        end: {
          leverage: 3,
          pancake_chef: 3,
          immovable_object: 2,
        },
      },
    },
    // OT
    {
      position: 'OT',
      templateName: 'Starter Normie',
      height: 81,
      weight: 340,
      strength: 1,
      speed: 1,
      agility: 10,
      stamina: 7,
      awareness: 6,
      confidence: 10,
      trait1: 'ol_tech_blocker',
      trait2: 'early_bloomer',
      trait3: 'thick_skin',
      skills: {
        start: {
          pass_block_technique: 30.0,
          pass_block_power: 30.0,
          pass_block_awareness: 20.0,
          run_block_technique: 60.0,
          run_block_power: 30.0,
          run_block_awareness: 30.0,
          lead_block_awareness: 0.0,
          block_consistency: 35.0,
          balance: 60.0,
          footwork: 20.0,
          quickness: 15.0,
          sprinting: 15.0,
          conditioning: 55.0,
          toughness: 60.0,
          snap_reaction: 30.0,
          heart: 30.0,
          intimidation: 0.0,
        },
        end: {
          pass_block_technique: 50.0,
          pass_block_power: 30.0,
          pass_block_awareness: 30.0,
          run_block_technique: 80.0,
          run_block_power: 50.0,
          run_block_awareness: 40.0,
          lead_block_awareness: 30.0,
          block_consistency: 70.0,
          balance: 70.0,
          footwork: 30.0,
          quickness: 25.0,
          sprinting: 25.0,
          conditioning: 65.0,
          toughness: 80.0,
          snap_reaction: 60.0,
          heart: 50.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          pancake_chef: 2,
        },
        end: {
          leverage: 3,
          pancake_chef: 3,
          immovable_object: 2,
        },
      },
    },
    // K
    {
      position: 'K',
      templateName: 'Standard Normie',
      height: 77,
      weight: 254,
      strength: 10,
      speed: 1,
      agility: 10,
      stamina: 1,
      awareness: 3,
      confidence: 10,
      trait1: 'k_leg_of_steel',
      trait2: 'early_bloomer',
      trait3: 'easy_going',
      skills: {
        start: {
          kick_accuracy: 0.0,
          kick_power: 0.0,
          kick_consistency: 0.0,
          kickoff_power: 0.0,
          tackle_technique: 0.0,
          tackle_power: 0.0,
          tackle_strip: 0.0,
          tackle_grip: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          kick_accuracy: 92.0,
          kick_power: 62.0,
          kick_consistency: 81.0,
          kickoff_power: 75.0,
          tackle_technique: 0.0,
          tackle_power: 0.0,
          tackle_strip: 0.0,
          tackle_grip: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 35.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 50.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          streaky: 3,
        },
        end: {
          streaky: 3,
          coverage_commander: 3,
        },
      },
    },
    // P
    {
      position: 'P',
      templateName: 'Standard Normie',
      height: 77,
      weight: 254,
      strength: 10,
      speed: 1,
      agility: 1,
      stamina: 10,
      awareness: 3,
      confidence: 10,
      trait1: 'k_leg_of_steel',
      trait2: 'early_bloomer',
      trait3: 'easy_going',
      skills: {
        start: {
          punt_hands: 0.0,
          punt_accuracy: 0.0,
          punt_power: 0.0,
          punt_consistency: 0.0,
          tackle_technique: 0.0,
          tackle_power: 0.0,
          tackle_strip: 0.0,
          tackle_grip: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 0.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 0.0,
          intimidation: 0.0,
        },
        end: {
          punt_hands: 30.0,
          punt_accuracy: 27.0,
          punt_power: 100.0,
          punt_consistency: 96.0,
          tackle_technique: 0.0,
          tackle_power: 0.0,
          tackle_strip: 0.0,
          tackle_grip: 0.0,
          balance: 0.0,
          footwork: 0.0,
          quickness: 0.0,
          sprinting: 0.0,
          vertical: 0.0,
          diving: 0.0,
          conditioning: 40.0,
          toughness: 0.0,
          snap_reaction: 0.0,
          heart: 90.0,
          intimidation: 0.0,
        },
      },
      abilities: {
        start: {
          coverage_commander: 3,
        },
        end: {
          coverage_commander: 3,
          entrapment: 3,
          pinned_deep: 2,
        },
      },
    },
  ];

  return templates.filter((x) => x.position === position);
};
